name: Build and deploy Node.js app to Azure Web App - conferencewebapppfe

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'  # Use the appropriate Node.js version here

      - name: Install dependencies
        run: yarn install

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'conferencewebapppfe'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_b8b9959ffbed4813b70cf016a5b7ca98 }}
          package: .
